Repository embox/embox, pull requests merged in 2019-06, with the labels that each got.

#1385 fs: Add filesystem_create in binfs_mount
  src/fs/driver/binfs/binfs.c
Labels: module:fs

#1386 scripts: Improve app_diff.sh
  scripts/app_diff.sh
Labels: scripts

#1387 mk: extbld: Forward -std CXX flag
  mk/extbld/toolchain.mk
Labels: buildsystem

#1393 libcoap: Rename
  third-party/lib/coap/Makefile
  third-party/lib/coap/Mybuild
  third-party/lib/coap/libcoap_embox_compat.h
Labels: easy

#1391 fb_direct_access: Use same picture for 32 and 16 bit buffers
  src/cmds/testing/fb_direct_access/fb_direct_access.c
Labels: easy

#1394 Fix gcc
  third-party/gcc/Makefile
Labels: module:thirdparty

#1390 stdint.h: Change 32-bit defines for compatibility
  src/compat/libc/include/inttypes.h
  src/compat/libc/include/stdint.h
Labels: compat

#1395 Add Mybuild syntax highlight for vim
  scripts/vim/mybuild.vim
Labels: scripts

#1392 OpenCV port
  platform/opencv/cmds/Mybuild
  platform/opencv/cmds/edges.cpp
  platform/opencv/cmds/version.cpp
  platform/opencv/templates/arm-qemu/build.conf
  platform/opencv/templates/arm-qemu/lds.conf
  platform/opencv/templates/arm-qemu/mods.config
  platform/opencv/templates/arm-qemu/rootfs/fruits.png
  platform/opencv/templates/arm-qemu/rootfs/network
  platform/opencv/templates/arm-qemu/system_start.inc
  src/compat/cxx/include/cmath
  src/compat/cxx/include/cstddef
  src/compat/posix/pthread/Mybuild
  third-party/lib/opencv/Makefile
  third-party/lib/opencv/Mybuild
  third-party/lib/opencv/patch.txt
Labels: in progress, module:platform, module:thirdparty

#1396 STLport: Add flag for compilation with GCC 9.1.0
  third-party/STLport/Makefile
Labels: easy, module:thirdparty

#1398 vmem: Clean
  src/compat/linux/include/asm-generic/dma-mapping.h
  src/drivers/block_dev/block_dev_common.c
  src/drivers/clock/Mybuild
  src/drivers/clock/mb_timer/Mybuild
  src/drivers/clock/mb_timer/mb_timer.c
  src/drivers/common/memory.c
  src/drivers/common/memory.h
  src/drivers/interrupt/Mybuild
  src/drivers/interrupt/irqmp/Mybuild
  src/drivers/interrupt/irqmp/irqmp.c
  src/drivers/interrupt/irqmp/irqmp.h
  src/drivers/interrupt/mb_intc/Mybuild
  src/drivers/interrupt/mb_intc/mb_intc.c
  src/drivers/interrupt/mb_intc/mb_intc.h
  src/drivers/pci/Mybuild
  src/drivers/serial/Mybuild
  src/drivers/serial/apbuart/Mybuild
  src/drivers/serial/apbuart/apbuart.c
  src/drivers/serial/xuartlite/Mybuild
  src/drivers/serial/xuartlite/xuartlite.c
  src/fs/driver/ramfs/ramfs.c
  src/fs/driver/tmpfs/tmpfs.c
  src/kernel/thread/stack_protect.c
  src/mem/mmap/mmap.c
  src/mem/phymem.c
  src/tests/mmu/mmu_core.c
Labels: easy, module:mem

#1399 Fix x86 exceptions
  mk/image.lds.S
  src/compat/cxx/core/cxx_invoke_constructors.c
  src/tests/c++/Mybuild
  src/tests/c++/exceptions.cpp
Labels: arch:x86

#1403 drivers/qspi/stm32f7_qspi: Initial implementation
  src/drivers/flash/qspi/Mybuild
  src/drivers/flash/qspi/stm32f7_qspi.c
  templates/arm/stm32f7cube/mods.config
Labels: module:drivers

#1401 Mmap stub
  src/compat/posix/sys/mman/Mybuild
  src/compat/posix/sys/mman/mmap_stub.c
Labels: compat, easy

#1404 cortexm_nvic: Fix initialization
  src/drivers/interrupt/cortexm/cortexm_nvic.c
  third-party/bsp/stmf7cube/arch.c
Labels: module:drivers

#1405 Fix timer init sequence
  src/compat/posix/proc/Proc.my
  src/include/kernel/time/time.h
  src/kernel/lthread/Mybuild
  src/kernel/sched/Mybuild
  src/kernel/thread/Mybuild
  src/kernel/time/Time.my
  src/kernel/time/clock_source.c
  src/kernel/time/jiffies.c
Labels: module:kernel

#1407 OpenCV port for STM32 F7 Discovery
  platform/opencv/cmds/version.cpp
  platform/opencv/templates/stm32f7discovery/build.conf
  platform/opencv/templates/stm32f7discovery/lds.conf
  platform/opencv/templates/stm32f7discovery/mods.config
  platform/opencv/templates/stm32f7discovery/readme
  platform/opencv/templates/stm32f7discovery/start_script.inc
  third-party/bsp/stmf7cube/Mybuild
  third-party/lib/opencv/Makefile
  third-party/lib/opencv/Mybuild
  third-party/lib/opencv/patch.txt
Labels: module:thirdparty

#1406 qt: Add new emboxfb plugin
  src/fs/syslib/idesc_mmap/idesc_mmap.c
  templates/x86/qt-fb/build.conf
  templates/x86/qt-fb/lds.conf
  templates/x86/qt-fb/mods.config
  templates/x86/qt-fb/start_script.inc
  third-party/qt/plugins/platforms/Emboxfb.my
  third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfb.pro
  third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfbintegration.cpp
  third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfbintegration.h
  third-party/qt/tree/src/plugins/platforms/emboxfb/main.cpp
Labels: module:thirdparty

#1408 Third party mirrors
  mk/extbld/lib.mk
  third-party/bsp/st_discovery_vl/Makefile
  third-party/bsp/st_f3/Makefile
  third-party/bsp/st_f4/Makefile
  third-party/bsp/stmf3cube/Makefile
  third-party/bsp/stmf4cube/Makefile
  third-party/bsp/stmf7cube/Makefile
  third-party/chibi-scheme/Makefile
  third-party/dropbear/Makefile
  third-party/freedesktop/mesa/glu/libglu_imx6/Makefile
  third-party/freedesktop/mesa/glu/libglu_osmesa/Makefile
  third-party/freedesktop/mesa/libdrm/etnaviv/Makefile
  third-party/freedesktop/mesa/libdrm/sw/Makefile
  third-party/freedesktop/mesa/mesa/mesa_etnaviv/Makefile
  third-party/freedesktop/mesa/mesa/mesa_sw/Makefile
  third-party/freedesktop/mesa/mesa_demos/Makefile
  third-party/lib/coap/Makefile
  third-party/lib/nuklear/Makefile
  third-party/lib/openlibm/Makefile
  third-party/lib/stb/Makefile
  third-party/lua/lib/luasocket/Makefile
  third-party/mruby/Makefile
  third-party/packetdrill/Makefile
  third-party/phoneme/Makefile
Labels: buildsystem, module:thirdparty

#1409 Work on lib/tftp
  src/cmds/bootloader/Qspi_loader.my
  src/cmds/bootloader/qspi_loader.c
  src/cmds/net/Tftp.my
  src/cmds/net/tftp.c
  src/lib/tftp/Mybuild
  src/lib/tftp/tftp.c
  src/lib/tftp/tftp.h
  templates/arm/stm32f7cube/mods.config
Labels: cmds, module:lib

#1410 Qt arm minimal
  src/drivers/video/pl110/Mybuild
  src/drivers/video/pl110/pl110.c
  templates/arm/qt-fb-small/build.conf
  templates/arm/qt-fb-small/lds.conf
  templates/arm/qt-fb-small/mods.config
  templates/arm/qt-fb-small/start_script.inc
  templates/arm/qt-fb-small/system_start.inc
  templates/x86/qt-vnc/start_script.inc
  templates/x86/test/qt-vnc/start_script.inc
  third-party/qt/Makefile
  third-party/qt/Mybuild
  third-party/qt/pkg_patch_for_qconfig.txt
  third-party/qt/qconfig-small.txt
Labels: module:thirdparty

#1412 Task foreach single
  src/include/kernel/task.h
  src/kernel/task/task_no_table.h
Labels: module:kernel

#1413 Update readme
  README.md
Labels: docs

#1414 Qt stm32
  src/cmds/bootloader/goto.c
  src/cmds/hardware/Memcpy.my
  src/cmds/hardware/memcpy.c
  src/drivers/video/stm32f7_lcd/Mybuild
  src/drivers/video/stm32f7_lcd/stm32f7_lcd.c
  templates/arm/qt-stm32f7discovery/build.conf
  templates/arm/qt-stm32f7discovery/lds.conf
  templates/arm/qt-stm32f7discovery/mods.config
  templates/arm/qt-stm32f7discovery/start_script.inc
  third-party/bsp/stmf7cube/Mybuild
  third-party/bsp/stmf7cube/sdram_init.c
  third-party/qt/Makefile
  third-party/qt/patch_cortex_m7.txt
  third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfbintegration.cpp
  third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfbintegration.h
Labels: module:thirdparty

#1415 cmds/hardware/mem rework
  src/cmds/hardware/Mem.my
  src/cmds/hardware/mem.c
Labels: cmds

#1417 Delete patch.txt from root directory
  patch.txt
Labels: easy
