Repository embox/embox, pull requests merged in 2019-12, with the labels that each got.

#1571 templates : change mount_test in x86/test/fs template
  templates/x86/test/fs/mods.config
Labels: templates

#1572 Work on partition support
  scripts/autotest/configs/mmc.sh
  scripts/autotest/run_scripts/run_qemu_mmc.sh
  scripts/autotest/testsuite/block_dev/partitions/test.exp
  scripts/disk/partitions.sh
  src/cmds/fs/chmod.c
  src/cmds/fs/ls.c
  src/cmds/fs/mount.c
  src/cmds/testing/block_dev/block_dev_test.c
  src/compat/libc/stdio/rename_dvfs.c
  src/compat/posix/fs/chown/chown_dvfs.c
  src/compat/posix/fs/dvfs/chmod.c
  src/compat/posix/fs/dvfs/xattr.c
  src/drivers/block_dev/block_dev.c
  src/drivers/block_dev/block_dev.h
  src/drivers/block_dev/block_dev_idesc_dvfs.c
  src/drivers/block_dev/block_dev_idesc_oldfs.c
  src/drivers/block_dev/partition/partition.c
  src/drivers/mmc/core/Mybuild
  src/drivers/mmc/core/mmc_host.c
  src/drivers/mmc/host/pl181/pl181.c
  src/fs/driver/fat/fat_dvfs.c
  src/fs/dvfs/compat.c
  src/fs/dvfs/dvfs.c
  src/fs/dvfs/dvfs_xattr.c
  src/fs/fuse/fuse_linux.c
  src/fs/rootfs_dvfs.c
Labels: module:drivers, module:fs

#1574 Lsblk
  src/cmds/hardware/lsblk/Mybuild
  src/cmds/hardware/lsblk/lsblk.c
  src/cmds/testing/block_dev/block_dev_test.c
  src/drivers/block_dev/block_dev.c
  src/drivers/block_dev/block_dev.h
  src/drivers/block_dev/ide/cdrom.c
  src/drivers/block_dev/ramdisk/ramdisk.c
  src/drivers/char/char_dev_dvfs/char_dev_dvfs.c
  src/drivers/flash/flash.c
  src/fs/driver/devfs/devfs_dvfs.c
  templates/x86/qemu/mods.config
  templates/x86/qemu/system_start.inc
Labels: cmds, module:drivers, module:fs

#1575 Fix DW MMC driver
  src/drivers/common/Mybuild
  src/drivers/common/memory.c
  src/drivers/common/memory.h
  src/drivers/mmc/host/dw_mmc/dw_mmc.h
  src/drivers/mmc/host/dw_mmc/dw_mmc_socfpga.c
Labels: module:drivers

#1577 fs/fat: Fix fat_get_next()
  src/fs/driver/fat/fat_common.c
Labels: module:fs

#1568 Fix telnet
  platform/gpio_http_admin/templates/stm32f4_discovery/mods.config
  src/cmds/net/telnetd/Makefile
  src/cmds/net/telnetd/Mybuild
  src/cmds/net/telnetd/telnet.h
  src/cmds/net/telnetd/telnet_util.c
  src/cmds/net/telnetd/telnetd.c
  src/kernel/thread/signal/Mybuild
  src/kernel/thread/signal/siginfoq.c
  templates/arm/stm32f4-discovery/mods.config
  templates/arm/stm32f764g-discovery/mods.config
  templates/arm/stm32f769i-discovery/mods.config
  templates/arm/test/units/mods.config
  templates/microblaze/test/units/mods.config
  templates/mips/test/units/mods.config
  templates/x86/test/fs/mods.config
  templates/x86/test/net/mods.config
  templates/x86/test/units/mods.config
Labels: cmds

#1582 filesystem rm test
  scripts/autotest/framework/cmd.exp
  scripts/autotest/testsuite/fs-ramfs/rm/test.exp
  scripts/autotest/testsuite/fs-vfat/rm
  src/fs/driver/fat/fat.h
  src/fs/driver/fat/fat_common.c
  src/fs/driver/fat/fat_dvfs.c
  src/fs/driver/fat/fat_oldfs.c
  src/fs/dvfs/dvfs.c
  src/fs/dvfs/dvfs_util.c
Labels: module:fs

#1583 Fix mount-related memory leaks
  scripts/autotest/run_scripts/run_qemu_mmc.sh
  scripts/autotest/testsuite/fs-vfat/mount/test.exp
  src/fs/driver/fat/fat_common.c
  src/fs/dvfs/dvfs.c
  src/fs/dvfs/dvfs.h
  src/fs/dvfs/dvfs_util.c
  src/fs/syslib/kfsop.c
Labels: module:fs

#1581 Ramfs
  src/fs/driver/ramfs/Mybuild
  src/fs/driver/ramfs/ramfs.h
  src/fs/driver/ramfs/ramfs_dvfs.c
  src/fs/driver/ramfs/ramfs_oldfs.c
Labels: module:fs

#1584 Clean/unify VFS
  src/cmds/fs/mkfs.c
  src/drivers/block_dev/block_dev_idesc.c
  src/fs/driver/cifs/cifs.c
  src/fs/driver/devfs/devfs_oldfs.c
  src/fs/driver/dfs/dfs.c
  src/fs/driver/ext2/ext2.c
  src/fs/driver/ext3/ext3.c
  src/fs/driver/ext4/ext4.c
  src/fs/driver/fat/Mybuild
  src/fs/driver/fat/fat_common.c
  src/fs/driver/fat/fat_dvfs.c
  src/fs/driver/fat/fat_oldfs.c
  src/fs/driver/fs_driver.c
  src/fs/driver/initfs/initfs.c
  src/fs/driver/initfs/initfs_dvfs.c
  src/fs/driver/iso9660/cdfs.c
  src/fs/driver/jffs2/jffs2.c
  src/fs/driver/nfs/nfs.c
  src/fs/driver/ntfs/ntfs.c
  src/fs/driver/ramfs/Mybuild
  src/fs/driver/ramfs/ramfs.h
  src/fs/driver/ramfs/ramfs_dvfs.c
  src/fs/driver/ramfs/ramfs_oldfs.c
  src/fs/driver/ramfs/ramfs_ops.c
  src/fs/dvfs/dvfs.h
  src/fs/dvfs/file_desc.c
  src/fs/dvfs/file_desc.h
  src/fs/file_desc.c
  src/fs/file_desc.h
  src/fs/syslib/kfile.c
  src/fs/syslib/kfsop.c
  src/include/fs/fs_driver.h
Labels: module:fs

#1585 Rework oldfs file_operations structure
  src/cmds/hardware/ide.c
  src/compat/posix/fs/dirent.c
  src/compat/posix/fs/open.c
  src/drivers/char/char_dev.c
  src/drivers/char/char_dev_dvfs/char_dev.h
  src/drivers/char/char_dev_stub.c
  src/drivers/usb/usb_driver.c
  src/drivers/usb/usb_driver_example.c
  src/fs/driver/binfs/binfs.c
  src/fs/driver/cifs/cifs.c
  src/fs/driver/devfs/devfs_oldfs.c
  src/fs/driver/ext2/ext2.c
  src/fs/driver/ext2/ext2_xattr.c
  src/fs/driver/ext3/ext3.c
  src/fs/driver/ext4/ext4.c
  src/fs/driver/fat/fat.h
  src/fs/driver/fat/fat_oldfs.c
  src/fs/driver/initfs/initfs.c
  src/fs/driver/iso9660/cdfs.c
  src/fs/driver/jffs2/jffs2.c
  src/fs/driver/nfs/nfs.c
  src/fs/driver/ntfs/ntfs.c
  src/fs/driver/pseudofs/pseudofs.c
  src/fs/driver/ramfs/ramfs_oldfs.c
  src/fs/dvfs/dvfs.h
  src/fs/file_desc.c
  src/fs/file_desc.h
  src/fs/mount_table.c
  src/fs/node.c
  src/fs/syslib/kfile.c
  src/fs/syslib/kfile_node.c
  src/fs/syslib/kfsop.c
  src/fs/syslib/nokfile.c
  src/fs/syslib/perm.c
  src/fs/syslib/perm_stub.c
  src/fs/vfs.c
  src/fs/xattr.c
  src/include/drivers/usb/usb_driver.h
  src/include/fs/ext2.h
  src/include/fs/file_desc.h
  src/include/fs/file_operation.h
  src/include/fs/fs_driver.h
  src/include/fs/kfile.h
  src/include/fs/kfsop.h
  src/include/fs/mount.h
  src/include/fs/node.h
  src/include/fs/path.h
  src/include/fs/perm.h
  src/include/fs/vfs.h
  src/include/fs/xattr.h
  src/security/no_security/no_security.c
  src/security/security.h
  src/security/smac/smac_security.c
  src/tests/fs/mount_table_test.c
  src/tests/fs/vfs.c
Labels: module:fs

#1588 Fat refactor
  src/fs/driver/fat/fat.h
  src/fs/driver/fat/fat_common.c
  src/fs/driver/fat/fat_dvfs.c
  src/fs/driver/fat/fat_oldfs.c
  src/fs/dvfs/file_desc.c
  src/fs/dvfs/file_desc.h
Labels: module:fs

#1587 kopen/kclose refactor
  src/fs/driver/initfs/initfs.c
  src/fs/driver/ramfs/ramfs.h
  src/fs/driver/ramfs/ramfs_dvfs.c
  src/fs/driver/ramfs/ramfs_oldfs.c
  src/fs/driver/ramfs/ramfs_ops.c
  src/fs/syslib/kfile.c
Labels: module:fs

#1590 fs/fat: Remove open() and close() from file_ops
  src/fs/driver/fat/fat_common.c
  src/fs/driver/fat/fat_dvfs.c
  src/fs/driver/fat/fat_oldfs.c
Labels: module:fs

#1589 fs: Rm 'idesc_mode' field from 'struct idesc'
  src/compat/posix/fs/dvfs/open.c
  src/compat/posix/fs/ftruncate.c
  src/compat/posix/fs/read.c
  src/compat/posix/fs/readv.c
  src/compat/posix/fs/write.c
  src/compat/posix/fs/writev.c
  src/compat/posix/idx/idesc_pipe.c
  src/compat/posix/idx/pipe_pty.c
  src/compat/posix/idx/poll.c
  src/compat/posix/sys/timerfd/timerfd.c
  src/drivers/char/char_dev.c
  src/drivers/char/char_dev_dvfs/char_dev_dvfs.c
  src/drivers/console/fbcon.c
  src/drivers/tty/serial/idesc_serial.c
  src/drivers/tty/serial/idesc_serial_oldfs.c
  src/fs/file_desc.c
  src/fs/idesc.c
  src/fs/syslib/idesc_mmap/idesc_mmap.c
  src/fs/syslib/kfile.c
  src/include/fs/idesc.h
  src/init/diag_fd.c
  src/kernel/task/idesc/index_descriptor.c
  src/net/socket/sock_factory.c
Labels: module:fs

#1591 drivers/net/dwc_gmac: Add 1gbit support
  src/drivers/net/dwc_gmac/dwc_gmac.c
  templates/arm/de0_nano_soc/mods.config
Labels: module:net

#1593 Fix initfs driver
  src/fs/driver/initfs/initfs_dvfs.c
Labels: easy, module:fs

#1596 libc/assert: Fix compilation for NDEBUG
  src/compat/libc/assert/assert_impl.h
  src/drivers/scsi/scsi.c
  src/drivers/tty/serial/idesc_serial.c
  src/drivers/usb/class/Mybuild
  src/drivers/usb/class/usb_class_cdc.c
  src/drivers/video/fb_devfs/fb_devfs.c
  src/fs/driver/fat/fat_common.c
  src/kernel/task/idesc/idesc_table.c
  src/mem/vmem/vmem.c
  src/net/socket/udp_sock.c
  src/util/dlist/dlist_debug.c
Labels: compat

#1597 Fix FAT12/FAT16
  src/fs/driver/fat/fat.h
  src/fs/driver/fat/fat_common.c
  src/fs/driver/fat/fat_dvfs.c
  src/fs/driver/fat/fat_oldfs.c
Labels: module:fs

#1595 Clean some fs drivers
  src/fs/driver/fat/Mybuild
  src/fs/driver/fat/fat_common.c
  src/fs/driver/fat/fat_dvfs.c
  src/fs/driver/fat/fat_fops.c
  src/fs/driver/fat/fat_oldfs.c
  src/fs/driver/ramfs/ramfs.h
  src/fs/driver/ramfs/ramfs_dvfs.c
  src/fs/driver/ramfs/ramfs_oldfs.c
  src/fs/driver/ramfs/ramfs_ops.c
Labels: module:fs

#1599 oldfs: Fix mounting block_dev in oldfs
  src/fs/driver/devfs/devfs_oldfs.c
Labels: module:fs

#1601 Fix FAT
  src/fs/driver/fat/fat_common.c
  src/fs/driver/fat/fat_dvfs.c
Labels: module:fs

#1602 fs/fat_old: Fix mount
  src/fs/driver/fat/fat_oldfs.c
Labels: module:fs

#1600 tcp: Fix tcp_write to enable send msg with several iov
  src/net/socket/tcp_sock.c
Labels: module:net

#1604 fat: oldfs: Fix fat_oldfs umount
  src/fs/driver/fat/fat_oldfs.c
Labels: module:fs

#1606 i2c tools
  src/cmds/hardware/i2c_tools/i2cdetect/Mybuild
  src/cmds/hardware/i2c_tools/i2cdetect/i2cdetect.c
  src/cmds/hardware/i2c_tools/i2cdump/Mybuild
  src/cmds/hardware/i2c_tools/i2cdump/i2cdump.c
  src/cmds/hardware/i2c_tools/i2cget/Mybuild
  src/cmds/hardware/i2c_tools/i2cget/i2cget.c
  src/cmds/hardware/i2c_tools/i2cset/Mybuild
  src/cmds/hardware/i2c_tools/i2cset/i2cset.c
Labels: cmds

#1607 i2c designware driver
  src/drivers/i2c/adapters/i2c_designware/Mybuild
  src/drivers/i2c/adapters/i2c_designware/i2c_designware.c
  src/drivers/i2c/adapters/i2c_designware/i2c_designware.h
  src/drivers/i2c/adapters/i2c_designware/i2c_designware_0.c
  src/drivers/i2c/adapters/i2c_designware/i2c_designware_1.c
  src/drivers/i2c/adapters/i2c_designware/i2c_designware_2.c
  src/drivers/i2c/adapters/i2c_designware/i2c_designware_3.c
  src/drivers/i2c/i2c.h
  templates/arm/de0_nano_soc/mods.config
Labels: module:drivers

#1608 adxl345
  src/cmds/hardware/sensors/adxl345/Mybuild
  src/cmds/hardware/sensors/adxl345/adxl345.c
  src/drivers/sensors/adxl345/Mybuild
  src/drivers/sensors/adxl345/adxl345.c
  src/drivers/sensors/adxl345/adxl345.h
  templates/arm/de0_nano_soc/mods.config
Labels: cmds, module:drivers

#1610 posix: Add <sys/un.h> with sockaddr_un structure
  src/compat/posix/include/sys/un.h
  third-party/dropbear/dropbear.patch
  third-party/dropbear/stubs.h
  third-party/fuse/fuse_linux/include/sys/un.h
  third-party/lib/boost/boost_embox_compat.h
  third-party/lua/lib/luasocket/include/sys/un.h
  third-party/samba/samba_embox_compat.h
  third-party/zeromq/zeromq_embox_compat.h
Labels: compat

#1613 Designware SPI driver
  src/cmds/hardware/spi/Mybuild
  src/cmds/hardware/spi/spi.c
  src/drivers/spi/dw_spi/Mybuild
  src/drivers/spi/dw_spi/dw_spi.c
  src/drivers/spi/dw_spi/dw_spi.h
  templates/arm/de0_nano_soc/mods.config
Labels: cmds, module:drivers

#1614 scripts/continuous/run.sh: Avoid system crash on running this script
  scripts/continuous/run.sh
Labels: scripts

#1603 ci: Enable vfat test
  scripts/continuous/fs/run.sh
  src/fs/driver/fat/fat_common.c
Labels: in progress, module:tests

#1615 Improve posix compat
  src/cmds/fs/df/Mybuild
  src/compat/posix/fs/statvfs/Mybuild
  src/compat/posix/include/unistd.h
  src/fs/fuse/core/Mybuild
  third-party/fuse/ext2fuse/Mybuild
  third-party/fuse/fuse/Mybuild
  third-party/fuse/fuse_linux/Mybuild
  third-party/ntfs-3g/Mybuild
  third-party/ntfs-3g/include/sys/statvfs.h
Labels: compat

#1618 Enable virtual folders on oldfs
  scripts/expect/fs_shell_commands_test.exp
  src/cmds/fs/mkdir.c
  src/compat/posix/fs/dvfs/fsop.c
  src/compat/posix/include/sys/stat.h
  src/fs/driver/ramfs/ramfs_oldfs.c
  src/fs/dvfs/dvfs.c
  src/fs/dvfs/dvfs.h
  src/fs/dvfs/dvfs_util.c
  src/fs/fuse/fuse_linux.c
  src/fs/rootfs_dvfs.c
  src/fs/syslib/kfsop.c
  templates/x86/test/fs/start_script.inc
  templates/x86/test/lang/start_script.inc
Labels: module:fs

#1619 STM32 SPI driver
  src/cmds/hardware/spi/Mybuild
  src/cmds/hardware/spi/spi.c
  src/drivers/spi/spi.c
  src/drivers/spi/spi.h
  src/drivers/spi/stm32/Mybuild
  src/drivers/spi/stm32/spi_conf_f4.h
  src/drivers/spi/stm32/stm32.c
  src/drivers/spi/stm32/stm32_spi.h
  src/drivers/spi/stm32/stm32_spi1.c
  src/drivers/spi/stm32/stm32_spi2.c
  templates/arm/stm32f4-discovery/mods.config
Labels: cmds, module:drivers, templates

#1594 Enable NFS test on Travis
  scripts/continuous/fs/run.sh
  src/fs/driver/nfs/Mybuild
  src/fs/driver/nfs/nfs.c
Labels: module:fs

#1620 Inode operations
  src/compat/posix/fs/chmod/chmod_old.c
  src/compat/posix/fs/dirent/dirent_oldfs.c
  src/compat/posix/fs/open/open_oldfs.c
  src/compat/posix/include/dirent_impl.h
  src/drivers/block_dev/block_dev.c
  src/drivers/char/char_dev.c
  src/fs/driver/cifs/cifs.c
  src/fs/driver/devfs/Mybuild
  src/fs/driver/devfs/devfs_oldfs.c
  src/fs/driver/devfs/devfs_stub.c
  src/fs/driver/ext2/ext2.c
  src/fs/driver/ext4/ext4.c
  src/fs/driver/fat/fat_oldfs.c
  src/fs/driver/jffs2/jffs2.c
  src/fs/dvfs/dvfs.h
  src/fs/file_desc.c
  src/fs/inode.c
  src/fs/inode.h
  src/fs/mount_table.c
  src/fs/syslib/kfile.c
  src/fs/syslib/kfile_node.c
  src/fs/syslib/kfsop.c
  src/fs/syslib/perm.c
  src/fs/vfs.c
  src/include/fs/dir_context.h
  src/include/fs/inode_operation.h
  src/tests/fs/permissions.c
  src/tests/security/smac.c
Labels: module:fs
