Repository embox/embox, pull requests merged in 2020-12, with the labels that each got.

#2275 nuklear: Remove deps on stm32 bsp from command
  project/nuklear/cmd/grfx_rawfb/Mybuild
Labels: easy

#2280 Minor fix some warnings with optimization
  src/cmds/net/netmanager/net_service.c
  src/compat/posix/time/strptime.c
Labels: easy

#2278 Fix dialog bootcode
  platform/dialog/da14695/arch.c
  src/arch/arm/armmlib/exception_table.S
  src/arch/arm/embox.lds.S
  src/arch/arm/head.S
Labels: arch:arm

#2279 thread: Add more log_debug to thread_allocator_heap
  src/kernel/thread/thread_allocator/thread_allocator_heap.c
Labels: easy

#2284 pty: Make pty count as module option
  src/compat/posix/idx/Idx.my
  src/compat/posix/idx/pipe_pty.c
Labels: easy

#2286 Fix ramfs dvfs
  src/drivers/block_dev/ramdisk/ramdisk.c
  src/drivers/block_dev/ramdisk/ramdisk.h
  src/fs/driver/ramfs/ramfs.h
  src/fs/driver/ramfs/ramfs_dvfs.c
  src/fs/driver/ramfs/ramfs_oldfs.c
  src/fs/driver/ramfs/ramfs_ops.c
Labels: module:fs

#2290 2283 add nucleo h745zi q
  board_config/nucleo_h745zi_q.conf.h
  platform/stm32/h7/nucleo_h745zi_q/Mybuild
  platform/stm32/h7/nucleo_h745zi_q/arch.c
  platform/stm32/h7/nucleo_h745zi_q/stm32h7xx_hal_conf.h
  platform/stm32/templates/h7/nucleo_h745zi_q/board.conf.h
  platform/stm32/templates/h7/nucleo_h745zi_q/build.conf
  platform/stm32/templates/h7/nucleo_h745zi_q/lds.conf
  platform/stm32/templates/h7/nucleo_h745zi_q/mods.conf
  platform/stm32/templates/h7/nucleo_h745zi_q/rootfs/network
  platform/stm32/templates/h7/nucleo_h745zi_q/system_start.inc
  src/compat/libc/math/math_builtins.h
  src/drivers/net/stm32cube/Mybuild
  src/drivers/net/stm32cube/stm32h7cube_eth.c
  src/drivers/net/stm32cube/stm32h7cube_eth.h
  src/drivers/serial/stm32_usart/Mybuild
  src/drivers/serial/stm32_usart/stm32_usart_conf_h7.h
  src/drivers/serial/stm32_usart/stm_hal_msp.c
  third-party/bsp/stmh7cube/Mybuild
  third-party/bsp/stmh7cube/cube/Makefile
  third-party/bsp/stmh7cube/cube/Mybuild
Labels: module:platform

#2299 Clean device subsystem
  src/cmds/blockdev.c
  src/cmds/fs/mkfs.c
  src/cmds/fs/mkramdisk.c
  src/cmds/hardware/ide.c
  src/cmds/testing/block_dev/block_dev_test.c
  src/drivers/block_dev/block_dev.c
  src/drivers/block_dev/block_dev.h
  src/drivers/block_dev/block_dev_idesc.c
  src/drivers/block_dev/ide/cdrom.c
  src/drivers/block_dev/ide/harddisk_dma.c
  src/drivers/block_dev/ide/harddisk_pio.c
  src/drivers/block_dev/ide/ide_drive.c
  src/drivers/block_dev/partition/partition.c
  src/drivers/block_dev/ramdisk/ramdisk.c
  src/drivers/char/char_dev.c
  src/drivers/common/device.c
  src/drivers/common/device.h
  src/drivers/flash/flash_fs.c
  src/drivers/mmc/core/mmc_host.c
  src/drivers/mmc/host/sdhci/imx6_sdhci.c
  src/drivers/scsi/scsi_disk.c
  src/drivers/scsi/scsi_disk_create.c
  src/fs/driver/devfs/devfs_common.c
  src/fs/driver/devfs/devfs_oldfs.c
  src/fs/driver/ext3/ext3.c
  src/fs/driver/ext4/ext4.c
  src/fs/driver/jffs2/jffs2.c
  src/fs/driver/ntfs/ntfs.c
  src/fs/dvfs/dvfs.c
  src/fs/syslib/kfsop.c
Labels: module:drivers, module:fs

#2302 qt: Enable cpu cache for stm32f74g template
  project/qt4/templates/stm32f746g_discovery/mods.conf
Labels: easy

#2307 minior: Update README.md
  README.md
Labels: easy

#2311 templates: Fix opencv build
  project/opencv/templates/arm-qemu/mods.conf
  project/opencv/templates/stm32f746g-discovery/mods.conf
  project/opencv/templates/stm32f769i-discovery/mods.conf
Labels: easy
