Repository embox/embox, pull requests merged in 2020-07, with the labels that each got.

#2087 Rework riscv interrupts
  src/arch/riscv/include/asm/interrupts.h
  src/arch/riscv/kernel/interrupt.c
  src/arch/riscv64/include/asm/interrupts.h
  src/arch/riscv64/kernel/interrupt.c
  src/drivers/clock/Mybuild
  src/drivers/clock/at91_pitc.c
  src/drivers/clock/cmsis_systick.c
  src/drivers/clock/cortexa9_timer/cortexa9_timer.c
  src/drivers/clock/cortexm_systick/cortexm_systick.c
  src/drivers/clock/dm816x/dm816x_timer.c
  src/drivers/clock/e2k/e2k.c
  src/drivers/clock/epit/epit.c
  src/drivers/clock/gpt/gpt.c
  src/drivers/clock/gptimer/gptimer.c
  src/drivers/clock/integrator_pit/integrator_pit.c
  src/drivers/clock/lapic_timer.c
  src/drivers/clock/mb_timer/mb_timer.c
  src/drivers/clock/mips_clk/mips_clk.c
  src/drivers/clock/omap3_clk/omap3_clk.c
  src/drivers/clock/pit/pit.c
  src/drivers/clock/pl031/pl031.c
  src/drivers/clock/ppc_clk/ppc_clk.c
  src/drivers/clock/raspi_systick.c
  src/drivers/clock/riscv_clk/Mybuild
  src/drivers/clock/riscv_clk/riscv_clk.c
  src/drivers/clock/usermode.c
  src/drivers/clock/xen.c
  src/drivers/interrupt/Mybuild
  src/drivers/interrupt/riscv_intc.c
  src/drivers/interrupt/riscv_plic/Mybuild
  src/drivers/interrupt/riscv_plic/riscv_plic.c
  src/drivers/interrupt/riscv_plic/riscv_plic.h
  src/drivers/net/cadence_gem/cadence_gem.c
  src/drivers/serial/sifive_uart/sifive_uart.c
  src/include/hal/clock.h
  src/kernel/time/clock_tick.c
  templates/riscv/qemu/mods.conf
  templates/riscv/sifive_e/mods.conf
  templates/riscv/sifive_u/mods.conf
  templates/riscv64/qemu/mods.conf
Labels: arch:risc-v

#2089 1993 enable build libopencv objdetect
  mk/flags.mk
  platform/opencv/templates/arm-qemu/mods.conf
  platform/opencv/templates/stm32f769i-discovery/mods.conf
  src/cmds/testing/cxx/stl_demo/algo/Mybuild
  src/cmds/testing/cxx/stl_demo/algo/algostuff.hpp
  src/cmds/testing/cxx/stl_demo/algo/sort1.cpp
  src/cmds/testing/cxx/threads/Mybuild
  src/cmds/testing/cxx/threads/cxx_threads_demo.cpp
  src/compat/cxx/include/cstddef
  src/compat/libc/ctype/ctype.c
  src/compat/libc/include/ctype.h
  src/compat/libc/wchar/wctype.c
  templates/arm/c++_demo/mods.conf
  templates/mips/c++_demo/mods.conf
  templates/sparc/c++_demo/mods.conf
  templates/x86/c++_demo/mods.conf
  third-party/gcc/patch.txt
  third-party/lib/opencv/Makefile
  third-party/lib/opencv/Mybuild
Labels: compat, module:thirdparty

#2100 Fix assembler code indentations to tabs
  src/arch/arm/armlib/boot/copy_excpt_table.S
  src/arch/arm/armlib/boot/high_excpt_table.S
  src/arch/arm/armlib/boot/low_excpt_table.S
  src/arch/arm/armlib/boot/reset_handler.S
  src/arch/arm/armlib/boot/static_excpt_table.S
  src/arch/arm/armlib/context/context_switch.S
  src/arch/arm/armlib/exceptions/exception_table.S
  src/arch/arm/armlib/monitor_exception_table.S
  src/arch/arm/armmlib/context_switch.S
  src/arch/arm/armmlib/exception_table.S
  src/arch/arm/lib/setjmp.S
  src/arch/microblaze/kernel/entry.S
  src/arch/microblaze/kernel/exception_table.S
  src/arch/microblaze/lib/ptregs_jmp.S
  src/arch/microblaze/lib/setjmp.S
  src/arch/mips/kernel/boot.S
  src/arch/mips/kernel/reset.S
  src/arch/ppc/kernel/boot.S
  src/arch/ppc/kernel/context_switch.S
  src/arch/ppc/kernel/entry.S
  src/arch/ppc/kernel/exception_table.S
  src/arch/ppc/kernel/irq_entry.S
  src/arch/ppc/lib/setjmp.S
  src/arch/riscv/kernel/boot.S
  src/arch/riscv/lib/setjmp.S
  src/arch/x86/kernel/exception_entry.S
  src/arch/x86/lib/setjmp.S
  src/arch/xen/boot.S
  src/arch/xen/lib/setjmp.S
  src/arch/xen/xen_header.S
Labels: easy

#2095 Switch build system to absolute paths
  mk/image2.mk
  mk/image3.mk
  mk/image_lib.mk
  mk/variables.mk
Labels: buildsystem

#2103 mk: Add ability to use external project folder
  .gitignore
  mk/load-mybuild.inc.mk
  mk/main.mk
  mk/variables.mk
Labels: buildsystem

#2106 Usb gadget cdc ethernet
  src/drivers/usb/gadget/ecm/Mybuild
  src/drivers/usb/gadget/ecm/ecm_gadget.c
  src/drivers/usb/gadget/ecm/ecm_gadget.h
  src/drivers/usb/gadget/ecm/ecm_net_card.c
  src/drivers/usb/gadget/ecm/f_ecm.c
  src/drivers/usb/gadget/gadget.c
  src/drivers/usb/gadget/gadget.h
  src/include/drivers/usb/usb_defines.h
  third-party/bsp/dialog/da14695/udc/da1469x_udc.c
Labels: module:drivers

#2115 Qt update to 4.8.7
  templates/arm/qt-stm32f7discovery/mods.conf
  third-party/qt/Makefile
  third-party/qt/examples/Animatedtiles.my
  third-party/qt/examples/Moveblocks.my
  third-party/qt/patch_cortex_m7.txt
  third-party/qt/pkg_patch.txt
  third-party/qt/pkg_patch_for_qconfig.txt
  third-party/qt/plugins/platforms/Emboxfb.my
  third-party/qt/plugins/platforms/Emboxvc.my
  third-party/qt/plugins/platforms/Minimal.my
  third-party/qt/plugins/platforms/Vnc.my
  third-party/qt/qconfig-small.txt
  third-party/qt/tree/src/plugins/platforms/emboxfb/emboxfbintegration.cpp
Labels: module:thirdparty
